### ISSUE TITLE
const !

### ISSUE THREAD

**Issue by mhammerc** [Hinato15/simple-todo-list-nodejs#1]
https://github.com/Hinato15/simple-todo-list-nodejs/blob/50cbc4ec7bb0efea3d51535cfb2067574874e30a/app.js#L1

Mettre `const` au lieu de `let` empêchera de faire `express = 42;` par inadvertence 😋 C'est en général une bonne pratique de mettre des `const` par défaut et `let` où on en a besoin 😋

**Comment by Hinato15** [comment]
Salut, déjà fait mais la version n'est pas encore en ligne

**Comment by mhammerc** [comment]
Bien joué :D !!!!!!
